export default {
    'PROVIDE_ACCESS': "OPEN",
    'USAGE_DURING_INTERVAL': "INTERVAL",
    'USAGE_UNTIL_DELETION': "DELETION",
    'DURATION_USAGE': "DURATION",
    'USAGE_LOGGING': "LOGGING",
    'N_TIMES_USAGE': "N TIME",
    'USAGE_NOTIFICATION': "NOTIFICATION",
    'PROHIBIT_ACCESS': "DENY",
    'CONNECTOR_RESTRICTED_USAGE': "CONNECTOR",
    'SECURITY_PROFILE_RESTRICTED_USAGE': "SECURITY PROFILE",
}